### ISSUE TITLE
Problem: modified-before and modified-after filters are not set

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/fpr2par#15]
Expected behaviour: 

For the following: 

* [x] file-formats, 
* [x] preservation-action-types, 
* [x] preservation-actions, 
* [x] and business rules requests, 

The `modified-before` and `modified-after` query filters/parameters are enabled so that fpr2par only returns those records whose local last modified date falls before and/or after those dates.

NOTE: the fpr_format_groups and fpr_tools dataset do not have a modified_date property so this filter cannot be applied to the PAR format-familes or tools response.

**Comment by ross-spencer** [comment]
Description from the action types section in the API document: 
```
The date filters should be supplied as ISO-8601 date times or dates, i.e. 
yyyy-MM-ddThh:mm:ss.SZ or yyyy-MM-dd. If no time information is supplied, 
then 00:00:00 in UTC will be assumed. This means that if you supply 
modified-after and modified-before dates of 2019-01-01 and 2019-12-31, you will 
not match any Preservation Action Types modified during the day of 31st 
December.
```

**Comment by peterVG** [comment]
I've tried to implement it for business rules here: https://github.com/artefactual-labs/fpr2par/blob/master/fpr2par/views.py#L954-#L961

But it's not functioning correctly. See the sample query at the bottom of the PAR API Requests menu or at the bottom of the Example PAR API requests list on the homepage.

**Comment by peterVG** [comment]
Fixed in https://github.com/artefactual-labs/fpr2par/commit/c7c9543fb4bdd7afed569f4abdc9dd637f5e06c2
