### ISSUE TITLE
Problem: fpr2par doesn't have any tests to validate its data against the PAR schema

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/fpr2par#24]

**Comment by ross-spencer** [comment]
The Hudmol branch might give us a more robust approach to validation where we need a custom resolver for the schema URIs. The example code is [here](https://github.com/artefactual-labs/archivematica-par/blob/5616c35669fa4ca1fcc7acb94c19c41d1e01b5b1/src/dashboard/src/components/api/par_validator.py). In #22 we replace the URIs with Github ones that will resolve.

**Comment by peterVG** [comment]
Addressed by https://github.com/artefactual-labs/fpr2par/pull/22
