### ISSUE TITLE
Problem: use constraints to list accepted file formats for PAR preservation actions.

### ISSUE THREAD

**Issue by mjaddis** [artefactual-labs/fpr2par#61]
A PAR preservation action defines the inputs to an action in terms of files and properties. For example, the input to a preservation action that uses Mediainfo to extract technical metadata would be the AV file to be processed.   There is only one input in this case: the file to have metadata extracted from.   

However, fpr2par lists multiple input files for mediainfo (133 of them), e.g. http://parcore.dev.archivematica.org:5000/api/par/preservation-actions/114c9525-d676-4fac-9962-4672faa924bb   There is one input file listed for each file format that mediainfo can support.   However, in the PAR data model this would be interpretted to mean that you need 133 input files in order to run mediainfo, which isn't the case.  

What I think is needed is for all the possible input file formats to be listed in a `constraints` section of a preservation action:

```
"constraints": {
      "additionalItems": false,
      "items": {
        "properties": {
          "allowedFormats": {
            "items": {
              "$ref": "http://www.parcore.org/schema/format.json/#"
            },
            "type": "array"
          }
```

There would be a single input file to the preservation action and then 133 allowed formats for that input file listed in the constraints.   

There is also a wider question of what entity in the FPR is mapped to a preservation action in PAR.   In the previous implementation of the PAR API (https://github.com/hudmol/archivematica/tree/par-api), each FPR rule was mapped to a separate preservation action.   For the MediaInfo case, this means 133 preservation actions, one for each different file format that Mediainfo can cope with.   The approach in fpr2par is different - it maps FPR commands to PAR preservation actions.   This is also valid - and perhaps better as it reduces the number of preservation actions - but it needs the file formats that can be accepted to be listed in a constraints block.

**Comment by peterVG** [comment]
Fixed in https://github.com/artefactual-labs/fpr2par/commit/e595327f9e4a2e554e5e68c4a7bfe696881cdd0c. See http://parcore.dev.archivematica.org:5000/api/par/preservation-actions/1628571b-c2cd-4822-afdb-53561400c7c4
