### ISSUE TITLE
Problem: the "preservation-action-type" header parameter is not implemented for business-rules responses

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/fpr2par#63]
The request header may contain a comma separated list of preservation-action-type GUIDs which should act as a filter on the response.

**Comment by ross-spencer** [comment]
Should be resolved by https://github.com/artefactual-labs/fpr2par/pull/73/commits/a880935bf3a03ef4be165910fefcd24bbf592a11

**Comment by peterVG** [comment]
Fixed in https://github.com/artefactual-labs/fpr2par/commit/a880935bf3a03ef4be165910fefcd24bbf592a11
