### ISSUE TITLE
Problem: the "guid" header parameter is not implemented for business-rules responses 

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/fpr2par#64]
The business-rules request header may contain a comma separated list of GUIDs which should act as a filter on the response.

**Comment by ross-spencer** [comment]
Should be resolved by https://github.com/artefactual-labs/fpr2par/pull/73/commits/23115577e8ccd00cd55def9a8d91eb65c8667031

**Comment by peterVG** [comment]
fixed by https://github.com/artefactual-labs/fpr2par/commit/23115577e8ccd00cd55def9a8d91eb65c8667031
