### ISSUE TITLE
Problem: the "file-format" header parameter is not implemented for business-rules responses

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/fpr2par#65]
The request header may contain a comma separated list of file-format id:names which should act as a filter on the response.

**Comment by ross-spencer** [comment]
Should be resolved by https://github.com/artefactual-labs/fpr2par/pull/73/commits/0d86ac328cce8ad89f77c4c54b5b26b9dd3bb7ff

**Comment by peterVG** [comment]
fixed in https://github.com/artefactual-labs/fpr2par/commit/0d86ac328cce8ad89f77c4c54b5b26b9dd3bb7ff
