### ISSUE TITLE
Problem: the "preservation-action-type" header parameter is not implemented for preservation-actions responses

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/fpr2par#66]
The request header may contain a  a comma separated list of preservation-action-type GUIDs
which should act as a filter on the response.

**Comment by ross-spencer** [comment]
Should be resolved by https://github.com/artefactual-labs/fpr2par/pull/73/commits/64a385ef564943c407072122da5bc175307d969f

**Comment by peterVG** [comment]
Fixed in https://github.com/artefactual-labs/fpr2par/commit/64a385ef564943c407072122da5bc175307d969f
