### ISSUE TITLE
Problem: the "tool" header parameter is not implemented for tools responses

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/fpr2par#69]
The request header may contain a a comma separated list of tool GUIDs
which should act as a filter on the response.

**Comment by ross-spencer** [comment]
Should be resolved by https://github.com/artefactual-labs/fpr2par/pull/73/commits/f69ce150e2831fc3dbcdf1405205620232e4f9c0

**Comment by peterVG** [comment]
Not working in my testing

**Comment by ross-spencer** [comment]
Oh, curious @peterVG, is there a specific `cURL` you're using? If I look for `unrar` doing the following then i retrieve a single result for that:

```
user@artefactual:~/git/artefactual-labs/fpr2par/fpr2par$ curl -v \
>     -H "Accept: application/json" \
>     -H "tool: 52621750-1f8f-410d-aa1b-eb0a34103d51" \
>     "http://127.0.0.1:5000/api/par/tools" 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 5000 (#0)
> GET /api/par/tools HTTP/1.1
> Host: 127.0.0.1:5000
> User-Agent: curl/7.58.0
> Accept: application/json
> tool: 52621750-1f8f-410d-aa1b-eb0a34103d51
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: application/json
< Content-Length: 260
< Server: Werkzeug/1.0.1 Python/3.6.9
< Date: Tue, 28 Apr 2020 13:02:28 GMT
< 
{
  "tools": [
    {
      "id": {
        "guid": "52621750-1f8f-410d-aa1b-eb0a34103d51", 
        "name": "unrar-free-001", 
        "namespace": "https://archivematica.org"
      }, 
      "toolName": "unrar-free", 
      "toolVersion": "0.0.1"
    }
  ]
}
* Closing connection 0
```

**Comment by peterVG** [comment]
Ah, I see the issue now. The PAR spec expects the header to be named "guid" which is what I was testing for but in your code you've named the header filter "tool" which does work in my re-testing.

**Comment by peterVG** [comment]
Fixed in https://github.com/artefactual-labs/fpr2par/commit/3d30fa2242684f132e8e95bb930a5ad8fb61ca19
